// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nareshit.service;


public class Book {
    protected java.lang.String isbn;
    protected java.lang.String title;
    protected java.lang.String author;
    protected double price;
    
    public Book() {
    }
    
    public Book(java.lang.String isbn, java.lang.String title, java.lang.String author, double price) {
        this.isbn = isbn;
        this.title = title;
        this.author = author;
        this.price = price;
    }
    
    public java.lang.String getIsbn() {
        return isbn;
    }
    
    public void setIsbn(java.lang.String isbn) {
        this.isbn = isbn;
    }
    
    public java.lang.String getTitle() {
        return title;
    }
    
    public void setTitle(java.lang.String title) {
        this.title = title;
    }
    
    public java.lang.String getAuthor() {
        return author;
    }
    
    public void setAuthor(java.lang.String author) {
        this.author = author;
    }
    
    public double getPrice() {
        return price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
}
