// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nareshit.service;

public interface IBookService extends java.rmi.Remote {
    public com.nareshit.service.Book searchBook(java.lang.String isbn) throws 
         java.rmi.RemoteException;
    public int registerBook(java.lang.String isbn, java.lang.String title, java.lang.String author, double price) throws 
         java.rmi.RemoteException;
    public int updateBook(java.lang.String isbn, java.lang.String title, java.lang.String author, double price) throws 
         java.rmi.RemoteException;
}
